name: tap_protocol
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  cbor: ^5.1.1
  crypto: ^3.0.2
  hex: ^0.2.0
  pointycastle: ^3.6.2
  secp256k1: ^0.3.0
  dart_secp256k1:
    path: "/Users/mohitsingh/Desktop/rnd/dart-secp256k1"
  ffi: ^2.0.1
  base32: ^2.1.3
  fast_base58: ^0.2.1
  bech32: ^0.2.1
  collection: ^1.17.0
